hosts:
    - <%= domain %>

<% if (multisite != 'No') { %>
multisite: <%= multisite %>
<% } %>

# Extensions
extensions:
<% extensions.forEach(function (extension) { -%>
  - <%= extension %>
<% }) -%>

# PHP Version
php: <%= php %>

# Database details
database:
    name: wordpress
    user: wordpress
    password: vagrantpassword
    prefix: wp_
